"""
Add DM Sent field to infractions model.

Revision ID: 3d9c7f4c3e4c
Revises: c551b4b47800
Create Date: 2021-11-10 22:26:00.101691
"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '3d9c7f4c3e4c'
down_revision = 'c551b4b47800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Commands auto generated by Alembic."""
    op.add_column('api_infraction', sa.Column('dm_sent', sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Commands auto generated by Alembic."""
    op.drop_column('api_infraction', 'dm_sent')
