"""
Reminder failures.

Revision ID: c551b4b47800
Revises: 01182f408d4c
Create Date: 2021-11-07 21:22:57.615793

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c551b4b47800"
down_revision = "01182f408d4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Commands auto generated by Alembic."""
    op.add_column("api_reminder", sa.Column("failures", sa.Integer(), nullable=False))


def downgrade() -> None:
    """Commands auto generated by Alembic."""
    op.drop_column("api_reminder", "failures")
